include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/firebase_options.dart

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false # TODO: Remove line, needed for the template